In [8]:
!pip install -q pandas

import pandas as pd

df_nos = pd.read_csv('c:/Users/00/OneDrive/Desktop/Rota_Segura/nos.csv')

df_prioridades = pd.read_csv("C:/Users/00/OneDrive/Desktop/Rota_Segura/prioridades.csv")

df_trechos = pd.read_csv("C:/Users/00/OneDrive/Desktop/Rota_Segura/trechos.csv")

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
df_nos

                     id                        nome        lat        lng
0   cem_03_de_ceilandia         CEM 03 DE CEILÂNDIA -15.827009 -48.098270
1              eqnm_3_5                    EQNM 3/5 -15.826121 -48.101898
2                 feira  Feira Central de Ceilândia -15.816945 -48.104074
3             guariroba             Metrô Guariroba -15.830668 -48.107097
4                   hrc     Hospital Regional (HRC) -15.815758 -48.096917
5           metroCentro      Metrô Ceilândia Centro -15.821791 -48.112413
6              pracaCid            Praça do Cidadão -15.812866 -48.102518
7             pracaTrab        Praça do Trabalhador -15.823125 -48.101253
8      qnm_3_conjunto_i            QNM 3 CONJUNTO I -15.822272 -48.104004
9                 qnm_5                       QNM 5 -15.827982 -48.100161
10         qnm_5_conj_o                QNM 5 CONJ O -15.825488 -48.100140
11     qnm_5_conjunto_i            QNM 5 CONJUNTO I -15.827330 -48.101173
12                qnm13           QNM 23 CONJUNTO I -15.829720 -48.093653
13                qnm17       QNM 17 (Hélio Prates) -15.814696 -48.099026
14     qnn_4_conjunto_i            QNN 4 CONJUNTO I -15.824969 -48.108104
15                qnn24           QNN 24 CONJUNTO I -15.837532 -48.107171
16     qnp_5_conjunto_i            QNP 5 CONJUNTO I -15.819024 -48.125679
17                 sesc              Sesc Ceilândia -15.820213 -48.121066
18             terminal          Terminal Ceilândia -15.805554 -48.121494

In [9]:
df_trechos

,id,via,de,para,nivel_base,nivel_efetivo,total_avaliacoes,comprimento_m,lat_origem,lng_origem,lat_destino,lng_destino
0,t01,Acesso Terminal–Metrô,terminal,metroCentro,3,3,0,2196,-15.805554,-48.121494,-15.821791,-48.112413
1,t02,Av. Hélio Prates,terminal,feira,3,3,0,3042,-15.805554,-48.121494,-15.816945,-48.104074
2,t03,Av. Hélio Prates,feira,qnm17,2,2,0,614,-15.816945,-48.104074,-15.814696,-48.099026
3,t04,Via interna QNM,feira,pracaCid,2,2,0,667,-15.816945,-48.104074,-15.812866,-48.102518
4,t05,Via N1,pracaCid,sesc,3,3,0,2750,-15.812866,-48.102518,-15.820213,-48.121066
5,t06,Travessa QNM 13/15,pracaCid,qnm13,1,1,0,2513,-15.812866,-48.102518,-15.829720,-48.093653
6,t07,Via QNM,qnm17,qnm13,2,2,0,1952,-15.814696,-48.099026,-15.829720,-48.093653
7,t08,Via Leste,terminal,hrc,2,2,0,3860,-15.805554,-48.121494,-15.815758,-48.096917
8,t09,Via interna QNN,sesc,hrc,1,1,0,3337,-15.820213,-48.121066,-15.815758,-48.096917
9,t10,Via do Metrô,metroCentro,pracaTrab,3,3,0,1703,-15.821791,-48.112413,-15.823125,-48.101253
10,t11,Via do Metrô,pracaTrab,guariroba,2,2,0,1376,-15.823125,-48.101253,-15.830668,-48.107097
11,t12,Via QNN 24,qnn24,pracaTrab,1,1,0,2446,-15.837532,-48.107171,-15.823125,-48.101253
12,t13,Via QNN,qnn24,feira,2,2,0,3263,-15.837532,-48.107171,-15.816945,-48.104074
13,t14,Via QNN–Guariroba,qnn24,guariroba,2,2,0,1164,-15.837532,-48.107171,-15.830668,-48.107097
14,t15,Av. Hélio Prates,terminal,qnn24,3,3,0,4198,-15.805554,-48.121494,-15.837532,-48.107171
15,t16,Via de ligação Sul,hrc,pracaTrab,1,1,0,1309,-15.815758,-48.096917,-15.823125,-48.101253
16,t17,QNM 17-HRC,qnm17,hrc,3,3,0,372,-15.814696,-48.099026,-15.815758,-48.096917
17,t18,METROCEILANDIA-QNM3CONJI,metroCentro,qnm_3_conjunto_i,2,2,0,1266,-15.821791,-48.112413,-15.822272,-48.104004
18,t19,METROCEIL-QNN4,metroCentro,qnn_4_conjunto_i,1,1,0,801,-15.821791,-48.112413,-15.824969,-48.108104
19,t20,QNN 4-QNN3,qnm_3_conjunto_i,qnn_4_conjunto_i,2,2,0,867,-15.822272,-48.104004,-15.824969,-48.108104
20,t21,QNM 3-PTRAB,qnm_3_conjunto_i,pracaTrab,3,3,0,408,-15.822272,-48.104004,-15.823125,-48.101253
21,t22,CEM03-QNM5CJI,cem_03_de_ceilandia,qnm_5_conjunto_i,2,2,0,690,-15.827009,-48.098270,-15.827330,-48.101173
22,t23,CEM03-QNM 5 CJ O,cem_03_de_ceilandia,qnm_5_conj_o,3,3,0,335,-15.827009,-48.098270,-15.825488,-48.100140
23,t24,QNM 5 CJ O/ EQNM 3/5,qnm_5_conj_o,eqnm_3_5,3,3,0,225,-15.825488,-48.100140,-15.826121,-48.101898
24,t25,EQNM 3/5- QNM 5 CJ I,qnm_5_conjunto_i,eqnm_3_5,3,3,0,160,-15.827330,-48.101173,-15.826121,-48.101898
25,t26,QNM 5 CJ - QNM 5,qnm_5_conjunto_i,qnm_5,1,1,0,176,-15.827330,-48.101173,-15.827982,-48.100161
26,t27,QNM 5-CEM03,cem_03_de_ceilandia,qnm_5,1,1,0,230,-15.827009,-48.098270,-15.827982,-48.100161
27,t28,CEM 03 - QNM 23,cem_03_de_ceilandia,qnm13,2,2,0,814,-15.827009,-48.098270,-15.829720,-48.093653
28,t29,EQNM 3/5-PRAÇATB,pracaTrab,eqnm_3_5,3,3,0,467,-15.823125,-48.101253,-15.826121,-48.101898
29,t30,PRAÇATB-QNM 5 CJ O,pracaTrab,qnm_5_conj_o,3,3,0,297,-15.823125,-48.101253,-15.825488,-48.100140
30,t31,QNP5-SESC,qnp_5_conjunto_i,sesc,2,2,0,714,-15.819024,-48.125679,-15.820213,-48.121066

In [10]:
df_prioridades

,id,via,nivel,sinal_policiamento,sinal_infraestrutura,pontuacao
0,t06,Travessa QNM 13/15,1,0,0,4
1,t09,Via interna QNN,1,0,0,4
2,t12,Via QNN 24,1,0,0,4
3,t16,Via de ligação Sul,1,0,0,4
4,t19,METROCEIL-QNN4,1,0,0,4
5,t26,QNM 5 CJ - QNM 5,1,0,0,4
6,t27,QNM 5-CEM03,1,0,0,4
7,t03,Av. Hélio Prates,2,0,0,2
8,t04,Via interna QNM,2,0,0,2
9,t07,Via QNM,2,0,0,2
10,t08,Via Leste,2,0,0,2
11,t11,Via do Metrô,2,0,0,2
12,t13,Via QNN,2,0,0,2
13,t14,Via QNN–Guariroba,2,0,0,2
14,t18,METROCEILANDIA-QNM3CONJI,2,0,0,2
15,t20,QNN 4-QNN3,2,0,0,2
16,t22,CEM03-QNM5CJI,2,0,0,2
17,t28,CEM 03 - QNM 23,2,0,0,2
18,t31,QNP5-SESC,2,0,0,2
19,t01,Acesso Terminal–Metrô,3,0,0,0
20,t02,Av. Hélio Prates,3,0,0,0
21,t05,Via N1,3,0,0,0
22,t10,Via do Metrô,3,0,0,0
23,t15,Av. Hélio Prates,3,0,0,0
24,t17,QNM 17-HRC,3,0,0,0
25,t21,QNM 3-PTRAB,3,0,0,0
26,t23,CEM03-QNM 5 CJ O,3,0,0,0
27,t24,QNM 5 CJ O/ EQNM 3/5,3,0,0,0
28,t25,EQNM 3/5- QNM 5 CJ I,3,0,0,0
29,t29,EQNM 3/5-PRAÇATB,3,0,0,0
30,t30,PRAÇATB-QNM 5 CJ O,3,0,0,0